-- MySQL Script generated by MySQL Workbench
-- Wed Jan  2 22:59:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ECommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ECommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ECommerce` DEFAULT CHARACTER SET utf8 ;
USE `ECommerce` ;

-- -----------------------------------------------------
-- Table `ECommerce`.`Utenti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ECommerce`.`Utenti` ;

CREATE TABLE IF NOT EXISTS `ECommerce`.`Utenti` (
  `idUtente` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(30) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUtente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`CarteCredito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ECommerce`.`CarteCredito` ;

CREATE TABLE IF NOT EXISTS `ECommerce`.`CarteCredito` (
  `idCarteCredito` INT NOT NULL AUTO_INCREMENT,
  `NCarta` VARCHAR(16) NOT NULL,
  `DataScadenza` DATE NOT NULL,
  `CVV` VARCHAR(3) NOT NULL,
  `IdCliente` INT NOT NULL,
  PRIMARY KEY (`idCarteCredito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ECommerce`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ECommerce`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Indirizzo` VARCHAR(45) NOT NULL,
  `Città` VARCHAR(45) NOT NULL,
  `Cap` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Ordine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ECommerce`.`Ordine` ;

CREATE TABLE IF NOT EXISTS `ECommerce`.`Ordine` (
  `IdOrdine` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `NCarta` VARCHAR(16) NOT NULL,
  `Pagato` TINYINT NOT NULL,
  PRIMARY KEY (`IdOrdine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`ProdottiInOrdine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ECommerce`.`ProdottiInOrdine` ;

CREATE TABLE IF NOT EXISTS `ECommerce`.`ProdottiInOrdine` (
  `IdOrdine` INT NOT NULL,
  `IdProdotto` INT NOT NULL,
  `NomeProdotto` VARCHAR(45) NOT NULL,
  `Quantità` FLOAT NOT NULL,
  `Prezzo` FLOAT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Prodotti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ECommerce`.`Prodotti` ;

CREATE TABLE IF NOT EXISTS `ECommerce`.`Prodotti` (
  `idProdotti` INT NOT NULL AUTO_INCREMENT,
  `CodiceProdotto` VARCHAR(45) NOT NULL,
  `Taglia` VARCHAR(45) NULL,
  `Genere` VARCHAR(45) NULL,
  `Colore` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Foto` VARCHAR(45) NULL,
  `Prezzo` FLOAT NULL,
  `Quantità` FLOAT NULL,
  `IvaVendita` FLOAT NULL,
  PRIMARY KEY (`idProdotti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Promozioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ECommerce`.`Promozioni` ;

CREATE TABLE IF NOT EXISTS `ECommerce`.`Promozioni` (
  `IdPromozione` INT NOT NULL AUTO_INCREMENT,
  `Sconto` FLOAT NOT NULL,
  `DataI` DATE NOT NULL,
  `DataF` DATE NULL,
  PRIMARY KEY (`IdPromozione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`ProdottiInCarrello`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ECommerce`.`ProdottiInCarrello` ;

CREATE TABLE IF NOT EXISTS `ECommerce`.`ProdottiInCarrello` (
  `IdProdotto` INT NOT NULL,
  `Quantità` FLOAT NOT NULL,
  `IdCarrello` INT NOT NULL,
  `IdProdottiInCarrello` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Carrello`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ECommerce`.`Carrello` ;

CREATE TABLE IF NOT EXISTS `ECommerce`.`Carrello` (
  `idCarrello` INT NOT NULL AUTO_INCREMENT,
  `IdCliente` VARCHAR(45) NOT NULL,
  `IdProdottoInCarrello` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCarrello`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
